@startuml

[*] --> clientchannel
state agentservice{
    clientchannel-->agentserver :远程调用
    agentserver-->agentserver :建立agent端的channel
    agentserver --> agentchannel:启用agentchannel
    state upstream{
        agentchannel --> upstreamlocation
        upstreamlocation--> upstreamlocation :定位到dst地址[可嵌入认证和鉴权]
        upstreamlocation --> loadbalance :负载均衡策略
        loadbalance-->dstconf :负载均衡获取dst配置[可嵌入认证和鉴权]
        loadbalance-->dstchannelId :或者负载均衡获取dstchannel[可嵌入认证和鉴权]
    }
    dstchannelId-->dstchannel:获取dstchannel
    dstconf-->dstchannel:建立dstchannel
}
dstchannel --> dstServer :远程调用
dstServer-->[*]

@enduml